name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Catalog Service
        uses: docker/build-push-action@v4
        with:
          context: ./catalog-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/catalog-service:latest

      - name: Build and Push Watchlist Service
        uses: docker/build-push-action@v4
        with:
          context: ./watchlist-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/watchlist-service:latest

      - name: Build and Push Recommender Service
        uses: docker/build-push-action@v4
        with:
          context: ./recommender-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/recommender-service:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest